In [1]:
import numpy as np

from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

In [2]:
sample_questions=["What’s your favorite way to spend a day off","What type of music are you into","What was the best vacation you ever took and why",
"Where’s the next place on your travel bucket list and why",'What are your hobbies, and how did you get into them',
'What are your hobbies, and how did you get into them','What was your favorite age growing up','What was the last thing you read',
'Would you say you’re more of an extrovert or an introvert',"What's your favorite ice cream topping",'What was the last TV show you binge-watched',
'Are you into podcasts or do you only listen to music','Do you have a favorite holiday  Why or why not',
'If you could only eat one food for the rest of your life, what would it be','Do you like going to the movies or prefer watching at home',
"What’s your favorite sleeping position?What’s your go-to guilty pleasure",'Hellow, how are you','how are you','how are you doing',
'What’s your favorite way to spend a day off','In the summer, would you rather go to the beach or go camping',
"What’s your favorite quote from a TV show/movie/book",'How old were you when you had your first celebrity crush', 'who was it',
"What's one thing that can instantly make your day better",'Do you have any pet peeves','Which meal is your favorite: breakfast, lunch, or dinner',
'What song always gets you out on the dance floor','When you were a kid','did you eat the crusts on your sandwich or not',
'What activity instantly calms you','how would you spend your birthday','What do you do on your commute to/from work',
'Are you a fan of musicals—why or why not',"What's your favorite season and why","What's the best joke you've ever heard",
"What’s your favorite way to spend a day off","What type of music are you into",'are you mad', 'can you do it']


In [3]:
sample_answers=["He who laughs last, thinks slowest","Everyone has a photographic memory. Some don't have film",
"A day without sunshine is like, well, night",'On the other hand, you have different fingers',
'Change is inevitable, except from a vending machine','I just got lost in thought','It was unfamiliar territory',
'When the chips are down, the buffalo is empty',"Seen it all, done it all, can't remember most of it",
"Those who live by the sword get shot by those who don't","I feel like I'm diagonally parked in a parallel universe",
"He's not dead, he's electroencephalographically challenged","You have the right to remain silent",
'Anything you say will be misquoted, then used against you','I wonder how much deeper the ocean would be without sponges',
'Honk if you love peace and quiet','Nothing is fool-proof to a sufficiently talented fool',
'It is hard to understand how a cemeteryraised its burial cost and blamed it on the cost of living', 
"Just remember...if the world didn't suck, we'd all fall off you are doing good",
"The 50-50-90 rule: Anytime you have a 50-50 chance of getting something right, there's a 90% probability you'll get it wrong",
"It is said that if you line up all the cars in the world end to end, someone would be stupid enough to try and pass them",
" yes You can't have everything","Latest survey shows that 3 out of 4 people make up 75% of the world's population",
"The things that come to those that wait may be the things left by those who got there first",
"A fine is a tax for doing wrong", 'A tax is a fine for doing well',"It was recently discovered that research causes cancer in rats",
"Everybody lies, but it doesn't matter since nobody listens",'I wished the buck stopped here, as I could use a few',
'I started out with nothing, and I still have most of it',"Light travels faster than sound",
"This is why some people appear bright until you hear them speak",' yes i can do it','no','yup','great','I am fine','sweet','ok','wow']

In [4]:
len(sample_questions)

40

In [5]:
len(sample_answers)

40

In [6]:
#defining class lables
labels1=np.ones(len(sample_questions),dtype=np.int32)

In [7]:
labels1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
labels2=np.zeros(len(sample_answers),dtype=np.int32)

In [9]:
labels2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
sample_data=sample_questions+sample_answers

In [11]:
sample_data

['What’s your favorite way to spend a day off',
 'What type of music are you into',
 'What was the best vacation you ever took and why',
 'Where’s the next place on your travel bucket list and why',
 'What are your hobbies, and how did you get into them',
 'What are your hobbies, and how did you get into them',
 'What was your favorite age growing up',
 'What was the last thing you read',
 'Would you say you’re more of an extrovert or an introvert',
 "What's your favorite ice cream topping",
 'What was the last TV show you binge-watched',
 'Are you into podcasts or do you only listen to music',
 'Do you have a favorite holiday  Why or why not',
 'If you could only eat one food for the rest of your life, what would it be',
 'Do you like going to the movies or prefer watching at home',
 'What’s your favorite sleeping position?What’s your go-to guilty pleasure',
 'Hellow, how are you',
 'how are you',
 'how are you doing',
 'What’s your favorite way to spend a day off',
 'In the summer, w

In [12]:
labels=np.concatenate((labels1,labels2))

In [13]:
print(labels,'\n',len(labels))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0] 
 80


In [14]:
vocab_size=1000

encoded_data=[one_hot(i,vocab_size) for i in sample_data]
encoded_data

[[51, 241, 215, 688, 753, 220, 182, 906, 579],
 [207, 399, 64, 386, 516, 344, 507],
 [207, 214, 469, 408, 48, 344, 658, 742, 920, 338],
 [352, 469, 725, 559, 377, 241, 163, 807, 997, 920, 338],
 [207, 516, 241, 651, 920, 377, 752, 344, 69, 507, 973],
 [207, 516, 241, 651, 920, 377, 752, 344, 69, 507, 973],
 [207, 214, 241, 215, 630, 821, 30],
 [207, 214, 469, 589, 359, 344, 375],
 [470, 344, 85, 258, 315, 64, 620, 533, 372, 620, 873],
 [122, 241, 215, 337, 208, 917],
 [207, 214, 469, 589, 720, 818, 344, 724, 445],
 [516, 344, 507, 830, 372, 854, 344, 879, 806, 753, 386],
 [854, 344, 293, 182, 215, 633, 338, 372, 338, 675],
 [233,
  344,
  701,
  879,
  601,
  102,
  996,
  398,
  469,
  827,
  64,
  241,
  55,
  207,
  470,
  698,
  709],
 [854, 344, 386, 211, 753, 469, 175, 372, 441, 924, 458, 25],
 [51, 241, 215, 381, 110, 51, 241, 140, 753, 950, 529],
 [82, 377, 516, 344],
 [377, 516, 344],
 [377, 516, 344, 883],
 [51, 241, 215, 688, 753, 220, 182, 906, 579],
 [395, 469, 706, 470, 3

In [15]:
length=17
padding_sent=pad_sequences(encoded_data, maxlen=length, padding='pre')
padding_sent

array([[  0,   0,   0, ..., 182, 906, 579],
       [  0,   0,   0, ..., 516, 344, 507],
       [  0,   0,   0, ..., 742, 920, 338],
       ...,
       [  0,   0,   0, ...,   0,   0, 598],
       [  0,   0,   0, ...,   0,   0, 287],
       [  0,   0,   0, ...,   0,   0, 231]])

In [16]:
len(padding_sent)

80

In [17]:
my_model= Sequential()
my_model.add(Embedding(vocab_size,1000,input_length=17))
my_model.add(Flatten())
my_model.add(Dense(1,activation='sigmoid'))

In [18]:
my_model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

In [19]:
my_model.fit(padding_sent,labels,epochs=10)

Epoch 1/10
3/3 [==============================] - 1s 21ms/step - loss: 0.6885 - accuracy: 0.5625
Epoch 2/10
3/3 [==============================] - 0s 25ms/step - loss: 0.6033 - accuracy: 0.7750
Epoch 3/10
3/3 [==============================] - 0s 25ms/step - loss: 0.5348 - accuracy: 0.9750
Epoch 4/10
3/3 [==============================] - 0s 24ms/step - loss: 0.4727 - accuracy: 0.9750
Epoch 5/10
3/3 [==============================] - 0s 28ms/step - loss: 0.4150 - accuracy: 0.9625
Epoch 6/10
3/3 [==============================] - 0s 28ms/step - loss: 0.3558 - accuracy: 0.9625
Epoch 7/10
3/3 [==============================] - 0s 24ms/step - loss: 0.3000 - accuracy: 0.9625
Epoch 8/10
3/3 [==============================] - 0s 24ms/step - loss: 0.2508 - accuracy: 0.9875
Epoch 9/10
3/3 [==============================] - 0s 28ms/step - loss: 0.2065 - accuracy: 0.9875
Epoch 10/10
3/3 [==============================] - 0s 24ms/step - loss: 0.1696 - accuracy: 0.9875


In [20]:
#prediction

sent_to_predict=['How are you', 'I am doing good', 'Are you Good']

encoded_data=[one_hot(i,1000) for i in sent_to_predict]
print(encoded_data)

[[377, 516, 344], [204, 287, 883, 249], [516, 344, 249]]


In [21]:
def predict(sent_to_predict):
    encoded_data=[one_hot(i,1000) for i in sent_to_predict]
    padding=pad_sequences(encoded_data, maxlen=length, padding='pre')
    for i in my_model.predict(padding):    
        if i<0.5:
            print('Answer')
        elif i>=0.5:
            print('Question')

In [22]:
predict(['How are you', 'I am doing good', 'Are you Good','you are doing good','are you sure'])

Question
Answer
Question
Answer
Question


In [25]:
predict(['i am doing good'])

Answer
